### ISSUE TITLE
How to follow YAGNI in your codebase.

### ISSUE THREAD

**Issue by ghost** [luigirazum/mv-mintodolist#6]
It appears [lodash](https://lodash.com/) is being used in your codebase for very simple operations which are already built into JavaScript. 

This violets _YAGNI_ principle. 

You could take the following steps to make your code better:
- Try to implement built in [Array.prototype.at()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) method [here](https://github.com/luigirazum/mv-mintodolist/blob/main/src/todols.js#L24).
- Please use  [Array.prototype.forEach()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) method [here](https://github.com/luigirazum/mv-mintodolist/blob/main/src/index.js#L87).

---

**P2P CR By Rashed and Francisco.**

**Comment by luigirazum** [comment]
Thank you both for your kindly help. 👌
Just letting you know that I removed the lodash library from the project. 👍

Cheers,
Luis 👋
